In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df  = pd.read_csv('C:/Users/Ola/Desktop/filess/NFLX.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,05/02/2018,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,06/02/2018,247.699997,266.700012,245.000000,265.720001,265.720001,12595800
2,07/02/2018,266.579987,272.450012,264.329987,264.559998,264.559998,8981500
3,08/02/2018,267.079987,267.619995,250.000000,250.100006,250.100006,9306700
4,09/02/2018,253.850006,255.800003,236.110001,249.470001,249.470001,16906900

In [2]:
df.shape

(1009, 7)

In [3]:
df.Date.unique()

array(['05/02/2018', '06/02/2018', '07/02/2018', ..., '02/02/2022',
       '03/02/2022', '04/02/2022'], dtype=object)

In [4]:
df.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [5]:
df.drop('Date', axis=1, inplace=True)
df.head(11)

          Open        High         Low       Close   Adj Close    Volume
0   262.000000  267.899994  250.029999  254.259995  254.259995  11896100
1   247.699997  266.700012  245.000000  265.720001  265.720001  12595800
2   266.579987  272.450012  264.329987  264.559998  264.559998   8981500
3   267.079987  267.619995  250.000000  250.100006  250.100006   9306700
4   253.850006  255.800003  236.110001  249.470001  249.470001  16906900
5   252.139999  259.149994  249.000000  257.950012  257.950012   8534900
6   257.290009  261.410004  254.699997  258.269989  258.269989   6855200
7   260.470001  269.880005  260.329987  266.000000  266.000000  10972000
8   270.029999  280.500000  267.630005  280.269989  280.269989  10759700
9   278.730011  281.959991  275.690002  278.519989  278.519989   8312400
10  277.739990  285.809998  276.609985  278.549988  278.549988   7769000

In [6]:
o= (df.Open.max())
o

692.349976

In [7]:
x = (df[['Open', 'High', 'Low', 'Close', 'Adj Close']])
x

            Open        High         Low       Close   Adj Close
0     262.000000  267.899994  250.029999  254.259995  254.259995
1     247.699997  266.700012  245.000000  265.720001  265.720001
2     266.579987  272.450012  264.329987  264.559998  264.559998
3     267.079987  267.619995  250.000000  250.100006  250.100006
4     253.850006  255.800003  236.110001  249.470001  249.470001
...          ...         ...         ...         ...         ...
1004  401.970001  427.700012  398.200012  427.140015  427.140015
1005  432.959991  458.480011  425.540009  457.130005  457.130005
1006  448.250000  451.980011  426.480011  429.480011  429.480011
1007  421.440002  429.260010  404.279999  405.600006  405.600006
1008  407.309998  412.769989  396.640015  410.170013  410.170013

[1009 rows x 5 columns]

In [8]:
x["Adj_Close"] = x["Adj Close"]
x.drop('Adj Close', axis=1)

            Open        High         Low       Close   Adj_Close
0     262.000000  267.899994  250.029999  254.259995  254.259995
1     247.699997  266.700012  245.000000  265.720001  265.720001
2     266.579987  272.450012  264.329987  264.559998  264.559998
3     267.079987  267.619995  250.000000  250.100006  250.100006
4     253.850006  255.800003  236.110001  249.470001  249.470001
...          ...         ...         ...         ...         ...
1004  401.970001  427.700012  398.200012  427.140015  427.140015
1005  432.959991  458.480011  425.540009  457.130005  457.130005
1006  448.250000  451.980011  426.480011  429.480011  429.480011
1007  421.440002  429.260010  404.279999  405.600006  405.600006
1008  407.309998  412.769989  396.640015  410.170013  410.170013

[1009 rows x 5 columns]

In [9]:
y = df.Volume
y.head()

0    11896100
1    12595800
2     8981500
3     9306700
4    16906900
Name: Volume, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=40)

In [11]:
from sklearn.naive_bayes import GaussianNB
le  = GaussianNB()
le.fit(X_train, y_train)

GaussianNB()

In [12]:
le.score(X_test,y_test)

0.0

In [48]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import HuberRegressor

In [49]:
model = Pipeline([('Rand', RandomForestRegressor())])
model2 = Pipeline([('linear', LinearRegression())])
model3 = Pipeline([('svm', SVC(C=10, kernel='linear'))])
model4 = Pipeline([('tree', DecisionTreeClassifier())])
model5 = Pipeline([('berli', LogisticRegression())])
model6 = Pipeline([('Lasso', Lasso())])
model7 = Pipeline([('Ridge', Ridge())])
model8 = Pipeline([('huber', HuberRegressor())])

In [50]:
def model_accuracy():
    scores=[]
    
    score1 = model.fit(X_train,y_train)
    scores.append(score1.score(X_test, y_test)),
    
    score2 = model2.fit(X_train,y_train)
    scores.append(score2.score(X_test, y_test)),
    
    score3 = model3.fit(X_train,y_train)
    scores.append(score3.score(X_test, y_test))
    
    score4 = model4.fit(X_train,y_train)
    scores.append(score4.score(X_test, y_test))
    
    score5 = model5.fit(X_train,y_train)
    scores.append(score5.score(X_test, y_test))
    
    score6 = model6.fit(X_train,y_train)
    scores.append(score6.score(X_test, y_test))
    
    score7 = model7.fit(X_train,y_train)
    scores.append(score7.score(X_test, y_test))
    
    score8 = model8.fit(X_train,y_train)
    scores.append(score8.score(X_test, y_test))
    
    return scores

In [52]:
model_accuracy()

C:\Users\Ola\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.659e+15, tolerance: 2.118e+12
  model = cd_fast.enet_coordinate_descent(

[0.27924035207069464,
 0.37731425687463493,
 0.0,
 0.0,
 0.0,
 0.4134120211770539,
 0.37731841641974595,
 0.35445321262187535]

**Linear model models happens to be the best with Lasso emerging with the highest accuracy acore.**

In [53]:
import numpy as np
def get_Volume(Open,High,Low,Close,Adj_Close):
    columns = np.zeros(len(x.columns))
    columns[0] = (Open)
    columns[1] = (High)
    columns[2] = (Low)
    columns[3] = (Close)
    columns[4] = (Adj_Close)
    
    return model6.predict([columns])[0]

In [54]:
get_Volume(234,423,284,592,254)

C:\Users\Ola\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(

85445923.63242275

In [55]:
get_Volume(262,267,250,254,254)

C:\Users\Ola\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(

13480448.057638742

In [56]:
from sklearn.metrics import classification_report
y_pred = model4.predict(X_test)
report=classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

     1367800       0.00      0.00      0.00       0.0
     1595500       0.00      0.00      0.00       0.0
     1621100       0.00      0.00      0.00       0.0
     1673900       0.00      0.00      0.00       0.0
     1736000       0.00      0.00      0.00       0.0
     1780700       0.00      0.00      0.00       0.0
     1867300       0.00      0.00      0.00       0.0
     1882800       0.00      0.00      0.00       1.0
     1906600       0.00      0.00      0.00       1.0
     1995900       0.00      0.00      0.00       0.0
     2012900       0.00      0.00      0.00       1.0
     2019300       0.00      0.00      0.00       0.0
     2039400       0.00      0.00      0.00       0.0
     2061500       0.00      0.00      0.00       1.0
     2065600       0.00      0.00      0.00       1.0
     2077400       0.00      0.00      0.00       1.0
     2126200       0.00      0.00      0.00       1.0
     2151300       0.00      0.00      0.00       1.0
     2176300       0.00      0.00      0.00       1.0
     2220300       0.00      0.00      0.00       1.0
     2250900       0.00      0.00      0.00       1.0
     2269000       0.00      0.00      0.00       0.0
     2309800       0.00      0.00      0.00       0.0
     2320200       0.00      0.00      0.00       0.0
     2334900       0.00      0.00      0.00       1.0
     2376300       0.00      0.00      0.00       1.0
     2390500       0.00      0.00      0.00       1.0
     2393200       0.00      0.00      0.00       1.0
     2411700       0.00      0.00      0.00       0.0
     2415600       0.00      0.00      0.00       1.0
     2423500       0.00      0.00      0.00       1.0
     2431900       0.00      0.00      0.00       0.0
     2434800       0.00      0.00      0.00       0.0
     2456200       0.00      0.00      0.00       0.0
     2504700       0.00      0.00      0.00       0.0
     2517900       0.00      0.00      0.00       1.0
     2582000       0.00      0.00      0.00       1.0
     2602000       0.00      0.00      0.00       1.0
     2681200       0.00      0.00      0.00       0.0
     2712500       0.00      0.00      0.00       0.0
     2720300       0.00      0.00      0.00       1.0
     2759000       0.00      0.00      0.00       1.0
     2764400       0.00      0.00      0.00       1.0
     2820200       0.00      0.00      0.00       1.0
     2859400       0.00      0.00      0.00       1.0
     2862500       0.00      0.00      0.00       1.0
     2866200       0.00      0.00      0.00       0.0
     2882500       0.00      0.00      0.00       1.0
     2887500       0.00      0.00      0.00       1.0
     2891900       0.00      0.00      0.00       0.0
     2894000       0.00      0.00      0.00       0.0
     2910300       0.00      0.00      0.00       1.0
     2943500       0.00      0.00      0.00       0.0
     2954200       0.00      0.00      0.00       1.0
     2973900       0.00      0.00      0.00       1.0
     2984500       0.00      0.00      0.00       1.0
     3002700       0.00      0.00      0.00       1.0
     3042200       0.00      0.00      0.00       0.0
     3067500       0.00      0.00      0.00       1.0
     3077800       0.00      0.00      0.00       1.0
     3104100       0.00      0.00      0.00       0.0
     3110900       0.00      0.00      0.00       0.0
     3124000       0.00      0.00      0.00       1.0
     3133900       0.00      0.00      0.00       1.0
     3160500       0.00      0.00      0.00       0.0
     3193400       0.00      0.00      0.00       1.0
     3198300       0.00      0.00      0.00       0.0
     3209100       0.00      0.00      0.00       0.0
     3227300       0.00      0.00      0.00       1.0
     3238900       0.00      0.00      0.00       0.0
     3245000       0.00      0.00      0.00       1.0
     3269000       0.00      0.00      0.00       0.0
     3271100       0.00      0.00      0.00       0.0
     3322900       0.00      0.00      0.00       1.0
     3330000       0.00      0.00      0.00       0.0
     3355900       0.00      0.00      0.00       0.0
     3360600       0.00      0.00      0.00       0.0
     3394900       0.00      0.00      0.00       1.0
     3438300       0.00      0.00      0.00       1.0
     3457000       0.00      0.00      0.00       0.0
     3474200       0.00      0.00      0.00       1.0
     3482300       0.00      0.00      0.00       0.0
     3484300       0.00      0.00      0.00       0.0
     3503100       0.00      0.00      0.00       1.0
     3505500       0.00      0.00      0.00       1.0
     3556900       0.00      0.00      0.00       1.0
     3598600       0.00      0.00      0.00       0.0
     3627200       0.00      0.00      0.00       0.0
     3669700       0.00      0.00      0.00       0.0
     3671700       0.00      0.00      0.00       1.0
     3682800       0.00      0.00      0.00       1.0
     3698100       0.00      0.00      0.00       0.0
     3703500       0.00      0.00      0.00       0.0
     3710000       0.00      0.00      0.00       1.0
     3721200       0.00      0.00      0.00       1.0
     3725900       0.00      0.00      0.00       1.0
     3726400       0.00      0.00      0.00       1.0
     3727200       0.00      0.00      0.00       0.0
     3732200       0.00      0.00      0.00       0.0
     3755600       0.00      0.00      0.00       0.0
     3767600       0.00      0.00      0.00       1.0
     3771500       0.00      0.00      0.00       0.0
     3774300       0.00      0.00      0.00       1.0
     3783700       0.00      0.00      0.00       1.0
     3787400       0.00      0.00      0.00       1.0
     3817500       0.00      0.00      0.00       0.0
     3820500       0.00      0.00      0.00       1.0
     3833500       0.00      0.00      0.00       1.0
     3879700       0.00      0.00      0.00       0.0
     3905500       0.00      0.00      0.00       0.0
     3938600       0.00      0.00      0.00       1.0
     3944300       0.00      0.00      0.00       1.0
     3944800       0.00      0.00      0.00       0.0
     3948000       0.00      0.00      0.00       0.0
     3955700       0.00      0.00      0.00       0.0
     3981800       0.00      0.00      0.00       0.0
     4021800       0.00      0.00      0.00       1.0
     4062400       0.00      0.00      0.00       0.0
     4079400       0.00      0.00      0.00       0.0
     4094500       0.00      0.00      0.00       1.0
     4096900       0.00      0.00      0.00       1.0
     4102200       0.00      0.00      0.00       0.0
     4114400       0.00      0.00      0.00       0.0
     4121500       0.00      0.00      0.00       0.0
     4134500       0.00      0.00      0.00       1.0
     4138600       0.00      0.00      0.00       1.0
     4145100       0.00      0.00      0.00       1.0
     4148700       0.00      0.00      0.00       1.0
     4177400       0.00      0.00      0.00       0.0
     4192700       0.00      0.00      0.00       0.0
     4229000       0.00      0.00      0.00       1.0
     4252900       0.00      0.00      0.00       0.0
     4288700       0.00      0.00      0.00       1.0
     4311500       0.00      0.00      0.00       1.0
     4325300       0.00      0.00      0.00       0.0
     4328100       0.00      0.00      0.00       0.0
     4353500       0.00      0.00      0.00       0.0
     4361000       0.00      0.00      0.00       1.0
     4382900       0.00      0.00      0.00       0.0
     4385200       0.00      0.00      0.00       0.0
     4386400       0.00      0.00      0.00       0.0
     4400200       0.00      0.00      0.00       1.0
     4408200       0.00      0.00      0.00       0.0
     4417500       0.00      0.00      0.00       1.0
     4444400       0.00      0.00      0.00       1.0
     4457800       0.00      0.00      0.00       1.0
     4475100       0.00      0.00      0.00       1.0
     4486100       0.00      0.00      0.00       0.0
     4509000       0.00      0.00      0.00       0.0
     4580400       0.00      0.00      0.00       1.0
     4584700       0.00      0.00      0.00       1.0
     4592700       0.00      0.00      0.00       0.0
     4598200       0.00      0.00      0.00       1.0
     4615500       0.00      0.00      0.00       0.0
     4621500       0.00      0.00      0.00       1.0
     4634100       0.00      0.00      0.00       1.0
     4659500       0.00      0.00      0.00       0.0
     4714500       0.00      0.00      0.00       1.0
     4718300       0.00      0.00      0.00       0.0
     4735700       0.00      0.00      0.00       1.0
     4746100       0.00      0.00      0.00       0.0
     4773500       0.00      0.00      0.00       1.0
     4777300       0.00      0.00      0.00       1.0
     4826200       0.00      0.00      0.00       1.0
     4860800       0.00      0.00      0.00       0.0
     4896400       0.00      0.00      0.00       1.0
     4896900       0.00      0.00      0.00       0.0
     4927900       0.00      0.00      0.00       1.0
     4935700       0.00      0.00      0.00       1.0
     4992600       0.00      0.00      0.00       0.0
     4995900       0.00      0.00      0.00       0.0
     5010900       0.00      0.00      0.00       0.0
     5019000       0.00      0.00      0.00       1.0
     5020100       0.00      0.00      0.00       0.0
     5023400       0.00      0.00      0.00       1.0
     5034800       0.00      0.00      0.00       1.0
     5052700       0.00      0.00      0.00       0.0
     5063700       0.00      0.00      0.00       1.0
     5111800       0.00      0.00      0.00       0.0
     5113100       0.00      0.00      0.00       1.0
     5131600       0.00      0.00      0.00       1.0
     5137300       0.00      0.00      0.00       0.0
     5158000       0.00      0.00      0.00       0.0
     5164500       0.00      0.00      0.00       0.0
     5166600       0.00      0.00      0.00       0.0
     5197600       0.00      0.00      0.00       1.0
     5230000       0.00      0.00      0.00       0.0
     5245100       0.00      0.00      0.00       1.0
     5263900       0.00      0.00      0.00       1.0
     5271400       0.00      0.00      0.00       1.0
     5277300       0.00      0.00      0.00       1.0
     5277400       0.00      0.00      0.00       0.0
     5294100       0.00      0.00      0.00       0.0
     5353000       0.00      0.00      0.00       0.0
     5386500       0.00      0.00      0.00       0.0
     5394700       0.00      0.00      0.00       1.0
     5422300       0.00      0.00      0.00       1.0
     5457500       0.00      0.00      0.00       0.0
     5460500       0.00      0.00      0.00       0.0
     5572700       0.00      0.00      0.00       1.0
     5594300       0.00      0.00      0.00       1.0
     5602500       0.00      0.00      0.00       1.0
     5608900       0.00      0.00      0.00       1.0
     5626200       0.00      0.00      0.00       1.0
     5629900       0.00      0.00      0.00       0.0
     5641900       0.00      0.00      0.00       0.0
     5657100       0.00      0.00      0.00       0.0
     5663100       0.00      0.00      0.00       1.0
     5667200       0.00      0.00      0.00       0.0
     5669900       0.00      0.00      0.00       1.0
     5685400       0.00      0.00      0.00       1.0
     5685500       0.00      0.00      0.00       1.0
     5691700       0.00      0.00      0.00       0.0
     5713900       0.00      0.00      0.00       0.0
     5748400       0.00      0.00      0.00       1.0
     5752200       0.00      0.00      0.00       0.0
     5770400       0.00      0.00      0.00       1.0
     5772800       0.00      0.00      0.00       1.0
     5805200       0.00      0.00      0.00       1.0
     5809300       0.00      0.00      0.00       0.0
     5821400       0.00      0.00      0.00       1.0
     5873100       0.00      0.00      0.00       0.0
     5878800       0.00      0.00      0.00       1.0
     5882600       0.00      0.00      0.00       1.0
     5895800       0.00      0.00      0.00       0.0
     5899500       0.00      0.00      0.00       1.0
     5910300       0.00      0.00      0.00       1.0
     5916300       0.00      0.00      0.00       0.0
     5928500       0.00      0.00      0.00       0.0
     5937800       0.00      0.00      0.00       0.0
     5948400       0.00      0.00      0.00       1.0
     5969000       0.00      0.00      0.00       1.0
     5990400       0.00      0.00      0.00       1.0
     5991900       0.00      0.00      0.00       0.0
     6029300       0.00      0.00      0.00       0.0
     6151300       0.00      0.00      0.00       1.0
     6179900       0.00      0.00      0.00       0.0
     6186100       0.00      0.00      0.00       1.0
     6209300       0.00      0.00      0.00       0.0
     6211900       0.00      0.00      0.00       1.0
     6218800       0.00      0.00      0.00       1.0
     6221000       0.00      0.00      0.00       1.0
     6227900       0.00      0.00      0.00       1.0
     6240200       0.00      0.00      0.00       1.0
     6248400       0.00      0.00      0.00       1.0
     6272100       0.00      0.00      0.00       0.0
     6280300       0.00      0.00      0.00       0.0
     6309400       0.00      0.00      0.00       0.0
     6324900       0.00      0.00      0.00       1.0
     6333800       0.00      0.00      0.00       1.0
     6347400       0.00      0.00      0.00       1.0
     6531700       0.00      0.00      0.00       1.0
     6583100       0.00      0.00      0.00       0.0
     6612600       0.00      0.00      0.00       0.0
     6768100       0.00      0.00      0.00       1.0
     6794400       0.00      0.00      0.00       0.0
     6797000       0.00      0.00      0.00       1.0
     6824800       0.00      0.00      0.00       1.0
     6905800       0.00      0.00      0.00       1.0
     6930400       0.00      0.00      0.00       0.0
     6954100       0.00      0.00      0.00       0.0
     6997900       0.00      0.00      0.00       2.0
     7014600       0.00      0.00      0.00       1.0
     7036100       0.00      0.00      0.00       0.0
     7131300       0.00      0.00      0.00       0.0
     7161500       0.00      0.00      0.00       0.0
     7328300       0.00      0.00      0.00       1.0
     7349900       0.00      0.00      0.00       0.0
     7355800       0.00      0.00      0.00       1.0
     7359100       0.00      0.00      0.00       1.0
     7487000       0.00      0.00      0.00       1.0
     7488400       0.00      0.00      0.00       0.0
     7541400       0.00      0.00      0.00       0.0
     7567500       0.00      0.00      0.00       1.0
     7604400       0.00      0.00      0.00       1.0
     7633100       0.00      0.00      0.00       0.0
     7643500       0.00      0.00      0.00       1.0
     7653500       0.00      0.00      0.00       0.0
     7655200       0.00      0.00      0.00       1.0
     7682000       0.00      0.00      0.00       1.0
     7684000       0.00      0.00      0.00       0.0
     7712300       0.00      0.00      0.00       1.0
     7722000       0.00      0.00      0.00       1.0
     7746200       0.00      0.00      0.00       0.0
     7769000       0.00      0.00      0.00       0.0
     7799100       0.00      0.00      0.00       1.0
     7810300       0.00      0.00      0.00       1.0
     7811100       0.00      0.00      0.00       0.0
     7817400       0.00      0.00      0.00       0.0
     7849400       0.00      0.00      0.00       1.0
     7849600       0.00      0.00      0.00       1.0
     7852400       0.00      0.00      0.00       0.0
     7864500       0.00      0.00      0.00       1.0
     7873900       0.00      0.00      0.00       1.0
     7944700       0.00      0.00      0.00       1.0
     7988700       0.00      0.00      0.00       0.0
     8153700       0.00      0.00      0.00       1.0
     8209500       0.00      0.00      0.00       0.0
     8278000       0.00      0.00      0.00       1.0
     8299900       0.00      0.00      0.00       0.0
     8306100       0.00      0.00      0.00       1.0
     8312400       0.00      0.00      0.00       1.0
     8353200       0.00      0.00      0.00       0.0
     8358000       0.00      0.00      0.00       0.0
     8437100       0.00      0.00      0.00       1.0
     8438800       0.00      0.00      0.00       1.0
     8448900       0.00      0.00      0.00       1.0
     8461300       0.00      0.00      0.00       0.0
     8467800       0.00      0.00      0.00       0.0
     8473800       0.00      0.00      0.00       1.0
     8616600       0.00      0.00      0.00       1.0
     8629600       0.00      0.00      0.00       0.0
     8650300       0.00      0.00      0.00       1.0
     8661300       0.00      0.00      0.00       1.0
     8670300       0.00      0.00      0.00       0.0
     8692500       0.00      0.00      0.00       0.0
     8755000       0.00      0.00      0.00       0.0
     8767200       0.00      0.00      0.00       1.0
     8786100       0.00      0.00      0.00       0.0
     8842300       0.00      0.00      0.00       0.0
     8848400       0.00      0.00      0.00       0.0
     8891500       0.00      0.00      0.00       1.0
     8966800       0.00      0.00      0.00       0.0
     9099500       0.00      0.00      0.00       1.0
     9113700       0.00      0.00      0.00       1.0
     9117300       0.00      0.00      0.00       1.0
     9158900       0.00      0.00      0.00       1.0
     9171100       0.00      0.00      0.00       1.0
     9230000       0.00      0.00      0.00       0.0
     9252500       0.00      0.00      0.00       0.0
     9266700       0.00      0.00      0.00       1.0
     9306700       0.00      0.00      0.00       1.0
     9322400       0.00      0.00      0.00       0.0
     9322500       0.00      0.00      0.00       0.0
     9345600       0.00      0.00      0.00       0.0
     9382900       0.00      0.00      0.00       0.0
     9416500       0.00      0.00      0.00       1.0
     9547600       0.00      0.00      0.00       1.0
     9605600       0.00      0.00      0.00       1.0
     9693100       0.00      0.00      0.00       1.0
     9705900       0.00      0.00      0.00       1.0
     9710400       0.00      0.00      0.00       0.0
     9822300       0.00      0.00      0.00       1.0
     9853600       0.00      0.00      0.00       1.0
     9905200       0.00      0.00      0.00       0.0
     9914900       0.00      0.00      0.00       0.0
     9915300       0.00      0.00      0.00       1.0
     9967100       0.00      0.00      0.00       1.0
    10013900       0.00      0.00      0.00       0.0
    10066700       0.00      0.00      0.00       1.0
    10101200       0.00      0.00      0.00       0.0
    10249400       0.00      0.00      0.00       0.0
    10268600       0.00      0.00      0.00       1.0
    10407900       0.00      0.00      0.00       1.0
    10414000       0.00      0.00      0.00       0.0
    10419700       0.00      0.00      0.00       0.0
    10427100       0.00      0.00      0.00       1.0
    10429400       0.00      0.00      0.00       1.0
    10475100       0.00      0.00      0.00       1.0
    10480800       0.00      0.00      0.00       1.0
    10499600       0.00      0.00      0.00       1.0
    10559900       0.00      0.00      0.00       1.0
    10622000       0.00      0.00      0.00       0.0
    10798500       0.00      0.00      0.00       1.0
    10809100       0.00      0.00      0.00       0.0
    10917200       0.00      0.00      0.00       1.0
    10992800       0.00      0.00      0.00       0.0
    11023000       0.00      0.00      0.00       0.0
    11120700       0.00      0.00      0.00       1.0

C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ola\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [57]:
get_Volume(262.000000,267.899994,250.029999,254.259995,254.25999)

C:\Users\Ola\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(

13761813.285919629

In [58]:
import pickle

In [59]:
pickle.dump(model6,open("NFLX_pickle_file.pickle", 'wb'))